config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users
  authenticate :user, ->(u) { u.superadmin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'pages/home'
  get 'sign-in-development/:id', to: 'pages#sign_in_development', as: :sign_in_development
  get 'set_locale', to: 'application#set_locale'
  get 'contact', to: 'pages#contact'
  post 'contact', to: 'pages#submit_contact'
  post 'notify-javascript-error', to: 'pages#notify_javascript_error'

  resource :sign_up
  resource :dashboard

  resource :my_account do
    get :change_email
    get :change_password
    patch :update_password
    get :change_language
    get :edit
    patch :update
  end

  resource :my_company do
    patch :submit_choose
    delete :remove_me_from
  end
  resources :company_users do
    collection do
      post :search
    end
  end

  namespace :admin do
    resource :dashboard do
      get :sample_error
      get :sample_error_in_javascript
      get :sample_error_in_javascript_ajax
      get :sample_error_in_sidekiq
    end
    resources :users do
      collection do
        post :search
      end
    end
  end
end

app/views/pages/contact.html.erb
<%
  login_layout t('contact')
%>

<p class='text-center'><%= t 'contact_description' %></p>
<%= bootstrap_form_for @contact, url: contact_path do |f| %>
  <%= f.email_field :email, required: true, disabled: current_user.present? %>
  <%= f.text_area :text, required: true %>
  <div class='mb-5'>
    <% if current_user&.confirmed? %>
      <%= f.submit t('send'), class: 'btn btn-lg btn-primary float-right' %>
    <% else %>
      <div class='d-inline-block'>
        <%= recaptcha_tags callback: 'enableRecaptchaButtons', size: 'compact' %>
      </div>
      <%= f.submit t('send'), class: 'btn btn-lg btn-primary float-right', 'data-recaptcha-button': 'true' %>
    <% end %>
  </div>
<% end %>

app/views/pages/home.html.erb
<%
  blank_layout
%>
<div class='bg-dark text-white'>
  <% if current_user %>
    <%= link_to "#{current_user.email} dashboard", dashboard_path, class: 'float-right text-white py-2 px-4' %>
  <% else %>
    <%= link_to 'Login', new_user_session_path, class: 'float-right text-white py-2 px-4' %>
  <% end %>
  <div class='text-center pt-5'>
    <%= image_tag 'logo.svg', class: 'login-logo--max-width' %>
    <p>My access to the data</p>
  </div>
  <hr class='border-white border-bottom' style='width: 80%'>
  <div class='container py-5 text-center'>
    <% if current_user %>
      <%= link_to 'Go to dashboard', dashboard_path %>
    <% else %>
      <h4>Create new account</h4>
      <p>Start scraping after you sign up</p>
      <%= link_to 'LEARN MORE', '#', class: 'btn btn-warning rounded-pill px-4 text-light' %>
      <div class='mt-5 mb-5'>
        <%= bootstrap_form_for @sign_up_company_form, url: sign_up_path, html: { 'data-validate': true } do |f| %>
          <div class='row'>
            <div class='col-sm-6 col-md-4 offset-md-2'>
              <%= f.email_field :email, placeholder: 'Enter Your Email', required: true, class: '' %>
              <%= f.password_field :password, placeholder: 'Enter Your Password', required: true, class: '' %>
            </div>
            <div class='col-sm-6 col-md-4'>
              <%= f.text_field :company, placeholder: 'Enter Company Name', required: true %>
              <%= f.text_field :name, placeholder: 'Enter Your Name', required: true, class: '' %>
            </div>
          </div>
          <div class='row'>
            <div class='col-md-8 offset-md-2'>
              <%= f.submit 'SIGN UP', class: 'btn btn-block btn-primary font-weight-bold text-uppercase' %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class='py-5 bg-secondary'>
    <h2 class='text-center'>What others say</h2>
    <div class='d-flex flex-column flex-sm-row justify-content-around align-items-center'>
      <% 2.times do %>
        <div class='d-flex flex-column flex-md-row'>
          <%= image_tag 'logo.svg', style: 'width: 150px' %>
          <div>
            <p class='p-3'>
              "I found the best deals"
              <br>
              <small class='font-italic'>Anna from Company</small>
            </p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class='p-5 text-center bg-light'>
    <%= link_to 'Contact us', contact_path, class: 'btn btn-light btn-lg' %>
  </div>
</div>