config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users
  authenticate :user, ->(u) { u.superadmin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'pages/home'
  get 'sign-in-development/:id', to: 'pages#sign_in_development', as: :sign_in_development
  get 'set_locale', to: 'application#set_locale'
  get 'contact', to: 'pages#contact'
  post 'contact', to: 'pages#submit_contact'
  post 'notify-javascript-error', to: 'pages#notify_javascript_error'

  resource :sign_up
  resource :dashboard

  resource :my_account do
    get :change_email
    get :change_password
    patch :update_password
    get :change_language
    get :edit
    patch :update
  end

  resource :my_company do
    patch :submit_choose
    delete :remove_me_from
  end
  resources :company_users do
    collection do
      post :search
    end
  end

  namespace :admin do
    resource :dashboard do
      get :sample_error
      get :sample_error_in_javascript
      get :sample_error_in_javascript_ajax
      get :sample_error_in_sidekiq
    end
    resources :users do
      collection do
        post :search
      end
    end
  end
end

app/controllers/my_companies_controller.rb
class MyCompaniesController < ApplicationUserController
  def show
    @datatable = CompanyUsersDatatable.new view_context
  end

  def edit
    @company = current_user.company
    render partial: 'form', layout: false
  end

  def update
    @company = current_user.company
    update_and_render_or_redirect_in_js @company, _company_params, my_company_path
  end

  def _company_params
    params.require(:company).permit(
      *Company::FIELDS
    )
  end
end

app/views/my_companies/_form.html.erb
<div id='remote-form'>
  <%= bootstrap_form_with model: @company, url: my_company_path, layout: :horizontal do |f| %>
    <%= f.text_field :name %>
    <div class='remote-form__actions'>
      <%= f.submit class: 'btn btn-primary'%>
    </div>
  <% end %>
</div>

app/views/my_companies/show.html.erb
<%
  breadcrumb t('my_company') => nil
%>
<div class='row'>
  <div class='col-sm-6'>
    <div class='card'>
      <div class='card-body'>
        <% if current_user.admin_of_a_current_company? %>
          <%= button_tag_open_modal edit_my_company_path, pull_right: true %>
        <% end %>
        <%= detail_view_list current_user.company, *Company::FIELDS %>
      </div>
    </div>
  </div>
  <div class='col-sm-6'>
    <div class='card'>
      <div class='card-body'>
        <%= button_tag_open_modal new_company_user_path do %>
          <i class="demo-icon icon-plus" aria-hidden="true"></i>
          <%= t_crud('add_new', User) %>
        <% end %>
        <%= @datatable.render_html search_company_users_path(format: :json) %>
      </div>
    </div>
  </div>
</div>
<% if current_user.company_users.size > 1 %>
  <div class='card'>
    <div class='card-body'>
      <h5 class='card-title'>
        <%= t('you_belongs_to_multiple_companies') %>
      </h5>
      <div class='text-center'>
        <p><%= t'please_choose_company_which_you_want_to_access' %></p>
        <% current_user.companies.by_name.each do |company| %>
          <div class='m-2 show-on-hover d-flex justify-content-start align-items-center'>
            <% if current_user.company == company %>
              <button class='btn btn-secondary' disabled><%= company.name %></button>
              <span class="badge badge-success"><%= t('current') %></span>
            <% else %>
              <%= form_tag submit_choose_company_path(company) do %>
                <%= button_tag company.name, class: 'btn btn-secondary' %>
              <% end %>
              <span></span>
            <% end %>
            <%= button_to remove_me_from_company_path(company_id: company), method: :delete, 'data-confirm': t_are_you_sure, title: t('remove_me_from_a_company'), class: 'btn btn-link show-on-hover-target' do %>
              <i class="text-danger fa fa-trash-alt" aria-hidden="true"></i>
              <%= t('delete') %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>