config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users
  authenticate :user, ->(u) { u.superadmin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'pages/home'
  get 'sign-in-development/:id', to: 'pages#sign_in_development', as: :sign_in_development
  get 'set_locale', to: 'application#set_locale'
  get 'contact', to: 'pages#contact'
  post 'contact', to: 'pages#submit_contact'
  post 'notify-javascript-error', to: 'pages#notify_javascript_error'

  resource :sign_up
  resource :dashboard

  resource :my_account do
    get :change_email
    get :change_password
    patch :update_password
    get :change_language
    get :edit
    patch :update
  end

  resource :my_company do
    patch :submit_choose
    delete :remove_me_from
  end
  resources :company_users do
    collection do
      post :search
    end
  end

  namespace :admin do
    resource :dashboard do
      get :sample_error
      get :sample_error_in_javascript
      get :sample_error_in_javascript_ajax
      get :sample_error_in_sidekiq
    end
    resources :users do
      collection do
        post :search
      end
    end
  end
end

app/views/layouts/_breadcrumb.html.erb
<nav aria-label="breadcrumb" class='d-flex'>
  <ol class="flex-grow-1 breadcrumb breadcrumb--no-margin-bottom">
    <li>
      <%= link_to root_path do %>
        <%# both png and svg have flickering effect with turbolinks %>
        <%= image_tag 'logo.svg', class: 'breadcrumb__image--max-width', title: t('home') %>
      <% end %>
    </li>
    <li class='breadcrumb-item d-none d-sm-block'>
      <%= link_to root_path do %>
        <%= t('home') %>
      <% end %>
    </li>
    <% fetch_breadcrumb_list.each_with_index do |(text, link), i| %>
      <% last_item = i == fetch_breadcrumb_list.length - 1 %>
      <li class="breadcrumb-item <%= 'active' if last_item %>" <%= 'aria-current="page"' if last_item %>>
        <% if link.present? %>
          <%= link_to link do %>
            <%= text %>
          <% end %>
        <% else %>
          <span id='breadcrumb-last'>
            <%= text %>
          </span>
        <% end %>
      </li>
    <% end %>
    <li class='ml-auto'>
      <%= bootstrap_form_tag url: 'root_path', layout: :inline do |f| %>
        <%= f.text_field :global_search, skip_label: true, class: 'form-control--skip-padding-in-height d-none-display-important d-none d-md-block mr-1', id: 'search-field', placeholder: t('search_site'), size: '10', wrapper_class: 'form-group--without-margin' %>
        <%= button_tag class: 'btn btn-link btn--no-padding d-md-none', type: 'button', 'data-controller': 'activate', 'data-action': 'activate#toggle', 'data-activate-selector': '#search-field' do %>
          <i class="demo-icon icon-search"></i>
        <% end %>
      <% end %>
    </li>
    <li>
      <% if current_user.present? %>
        <%= button_tag class: "btn btn-link btn--no-padding", type: 'button', 'data-controller': 'activate', 'data-action': 'activate#toggle', 'data-activate-selector': '#sidebar,.sidebar__overlay' do %>
          <i class="demo-icon icon-menu d-sm-none"></i>
          <span class='d-none d-sm-block'><%= current_user.email %></span>
        <% end %>
      <% else %>
        <div class='mx-2'>
          <%= link_to t('contact'), contact_path, class: '' %>
          <%= link_to t('my_devise.register'), new_user_registration_path, class: 'btn btn-info btn--no-padding px-2' %>
          <%= link_to t('my_devise.sign_in'), new_user_session_path, class: 'btn btn-primary btn--no-padding px-2' %>
        </div>
      <% end %>
    </li>
  </ol>
  <div class='align-self-center'>
  </div>
</nav>

app/views/layouts/_choose_language.html.erb
<a class='nav-link dropdown-toggle <%= 'p-0' unless login_layout? %>' href='#' id='navbarDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
  <%= image_tag "flagpedia.net/#{locale}.png", class: 'flag--width', 'data-test': 'language-holder' %>
</a>
<div class="dropdown-menu dropdown-menu--without-min-width" aria-labelledby="navbarDropdown">
  <% I18n.available_locales.each do |locale| %>
    <%= link_to set_locale_path(locale: locale), 'data-turbolinks': false, class: 'dropdown-item' do %>
      <%= image_tag "flagpedia.net/#{locale}.png", class: 'flag--width' %>
      <%= t("language_name.#{locale}") %>
    <% end %>
  <% end %>
</div>

app/views/layouts/_flash_notice_alert_jbox.html.erb
<% if notice.present? %>
  <div data-controller='flash' data-flash-message='<%= notice %>'>
    <div data-test='notice-holder' class='d-none-display'><%= notice %></div>
    <button class='flash-notice-alert-jbox__repeat' data-action='flash#show' title='<%= t('last_message') %>'><i class="demo-icon icon-cw"></i></button>
  </div>
<% end %>
<% if alert.present? %>
  <div data-controller='flash' data-flash-message='<%= alert %>' data-flash-alert='true'>
    <div data-test='alert-holder' class='d-none-display'><%= alert %></div>
    <button class='flash-notice-alert-jbox__repeat' data-action='flash#show' title='<%= t('last_message') %>'><i class="demo-icon icon-cw"></i></button>
  </div>
<% end %>

app/views/layouts/_login_layout.html.erb
<%= render 'layouts/choose_language' %>
<% if current_user %>
  <div class='text-right pr-2'>
    <strong><%= current_user.email %></strong>
    <%= link_to t('my_devise.sign_out'), destroy_user_session_path, method: :delete %>
  </div>
<% end %>
<div class='text-center mt-2'>
  <%= link_to root_path do %>
    <%= image_tag 'logo.svg', class: 'login-logo--max-width mx-auto p-2' %>
  <% end %>
  <h2><%= login_title %></h2>
</div>
<div class='container'>
  <div class='login-wrapper--max-width mx-auto'>
    <div class='login--max-width mx-auto bg-white shadow p-4'>
      <%= yield %>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<%# on responsive there are two different horizontal navigations, one for admin and one for non admin
  breakpoint is sm
%>
<%
  left_navigation ||= false
%>
<div class='bg-light <%= left_navigation ? 'd-none d-sm-inline-block text-left left-navigation--min-width' : 'body__sticky-footer d-sm-none' %>'>
  <ul class='nav nav-pills <%= left_navigation ? 'flex-column ' : 'justify-content-around flex-nowrap ' %>'>
    <li class='nav-item flex-fill'>
      <%= link_to dashboard_path, class: "nav-link nav-link--no-padding rounded-0 #{'active' if params[:controller] == 'dashboards'}" do %>
        <div class='d-flex flex-column-reverse d-sm-inline-flex flex-sm-row align-items-center'>
          <i class='demo-icon icon-gauge mx-1' aria-hidden='true'></i>
          <span><%= t('dashboard') %></span>
        </div>
      <% end %>
    </li>
    <% if current_user&.superadmin? %>
      <li class='nav-item d-none d-sm-block'>
        <span class='text-success'>
          <%= t('admin_pages') %>
        </span>
      </li>
      <li class='nav-item d-none d-sm-block'>
        <%= link_to "<i class='demo-icon icon-gauge mx-1'></i>#{t('dashboard')}".html_safe, admin_dashboard_path, class: "nav-link nav-link--no-padding rounded-0 #{'active' if params[:controller] == 'admin/dashboard'}" %>
        <%= link_to "<i class='demo-icon icon-user-o mx-1'></i>#{User.model_name.human(count: 2)}".html_safe, admin_users_path, class: "nav-link nav-link--no-padding rounded-0 #{'active' if params[:controller] == 'admin/users'}" %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/_sidebar.html.erb
<nav id='sidebar' class=''>
  <div class='d-flex align-items-center'>
    <div class='text-secondary'><%= truncate current_user.email, length: 34 %></div>
    <div class='ml-auto'>
      <%= button_tag class: 'btn btn-link btn--no-padding', 'data-controller': 'activate', 'data-action': 'activate#toggle', 'data-activate-selector': '#sidebar,.sidebar__overlay' do %>
        <i class="demo-icon icon-window-close-o font-size--1-5"></i>
      <% end %>
    </div>
  </div>
  <div class='list-group list-group-flush'>
    <%= link_to "<i class='demo-icon icon-gauge mx-1'></i>#{t('home')}".html_safe, root_path, class: "list-group-item list-group-item-action text-primary #{'active' if params[:controller] == 'pages' && params[:action] != 'contact'}" %>
    <%= link_to "<i class='demo-icon icon-building mx-1'></i>#{t('my_company')}".html_safe, my_company_path, class: "list-group-item list-group-item-action text-primary #{'active' if params[:controller] == 'my_companies'}" %>
    <%= link_to "<i class='demo-icon icon-wrench mx-1'></i>#{t('my_account')}".html_safe, my_account_path, class: "list-group-item list-group-item-action text-primary #{'active' if params[:controller] == 'my_accounts'}" %>
    <%= link_to "<i class='demo-icon icon-question-circle-o mx-1' aria-hidden='true'></i>#{t('contact')}".html_safe, contact_path, class: "list-group-item list-group-item-action text-primary #{'active' if params[:controller] == 'pages' && params[:action] == 'contact'}" %>
    <div class='d-sm-none'>
      <%# here are the links that we hide in navigation on responsive %>
      <% if current_user.superadmin? %>
        <span class='text-success'>
          <%= t('admin_pages') %>
        </span>
        <%= link_to "<i class='demo-icon icon-gauge mx-1'></i>#{t('dashboard')}".html_safe, admin_dashboard_path, class: "list-group-item list-group-item-action text-primary #{'active' if params[:controller] == 'admin/dashboard'}" %>
        <%= link_to "<i class='demo-icon icon-user-o mx-1'></i>#{User.model_name.human(count: 2)}".html_safe, admin_users_path, class: "list-group-item list-group-item-action text-primary #{'active' if params[:controller] == 'admin/users'}" %>
      <% end %>
    </div>
    <%= link_to "<i class='icon-logout mx-1'></i>#{t('my_devise.sign_out')}".html_safe, destroy_user_session_path, method: :delete, class: 'list-group-item list-group-item-action text-primary' %>
  </div>
</nav>
<div class='sidebar__overlay' data-controller='activate' data-action='click->activate#toggle' data-activate-selector='#sidebar,.sidebar__overlay'></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='<%= I18n.locale %>' android-app='<%= android_app? %>'>
  <head>
    <title><%= Const.common[:name] %>: <%= fetch_title %></title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%# Google Font %>
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
  </head>

  <body class='
    <%= 'body__sticky-footer--wrapper' unless login_layout? %>
    <%= 'bg-success' if Rails.application.credentials.is_staging %>
    '>
    <% if login_layout? %>
      <%= render 'layouts/login_layout' %>
    <% elsif blank_layout? %>
      <%= yield %>
    <% else %>
      <% if current_user.present? %>
        <%= render 'layouts/sidebar' %>
      <% end %>
      <%= render 'layouts/breadcrumb' %>

      <div class='d-flex align-items-stretch body__content'>
        <%= render 'layouts/navigation', left_navigation: true %>
        <div class='pt-2 px-3 body__content_without_left-navigation'>
          <%= yield %>
        </div>
      </div>

      <%= render 'layouts/navigation' %>
    <% end %>
    <%= render 'layouts/flash_notice_alert_jbox' %>
  </body>
</html>